org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
kotlin.code.style=official
org.gradle.java.home=/usr/lib/jvm/java-25-jdk

android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false


# Suppress the library constraints warning
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
